# # Core
db:
  redis:
      host: 'localhost'
      port: 6379
      namespace: EG
plugins:
  store_token:
    package: './plugins/store_token.js'
  logout:
    package: './plugins/logout.js'
  validate_session:
    package: './plugins/validate_session.js'
